name: component_sdk
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  country_picker: ^2.0.19
  flutter:
    sdk: flutter

  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
